<!DOCTYPE html>
<html>
<head>
    <title>Queue Report - {{ $date }}</title>
    <style>
        body { font-family: sans-serif; font-size: 11px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; padding: 0; color: #004a99; }
        .summary { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table, th, td { border: 1px solid #ddd; }
        th, td { padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .badge { padding: 3px 6px; border-radius: 4px; font-size: 9px; }
        .completed { color: green; }
        .no_response { color: red; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ACLC College of Mandaue</h1>
        <h3>Registrar's Office Queue Report</h3>
        <p>Activity Date: {{ \Carbon\Carbon::parse($date)->format('F j, Y') }}</p>
    </div>

    <div class="summary">
        <strong>Total Transactions:</strong> {{ count($entries) }}<br>
        <strong>Report Generated:</strong> {{ now()->format('Y-m-d h:i A') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Ticket</th>
                <th>Student</th>
                <th>Purpose</th>
                <th>Status</th>
                <th>Wait Start</th>
                <th>Served At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($entries as $entry)
            <tr>
                <td><strong>{{ $entry->ticket_number }}</strong></td>
                <td>{{ $entry->name }}</td>
                <td>{{ $entry->purpose }}</td>
                <td class="{{ $entry->status }}">{{ ucfirst($entry->status) }}</td>
                <td>{{ $entry->created_at->format('h:i A') }}</td>
                <td>{{ $entry->served_at ? $entry->served_at->format('h:i A') : '--' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div style="margin-top: 50px;">
        <p>Generated by ACLC Queueing System</p>
    </div>
</body>
</html>
